name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up Maven settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>gitlab-maven</id>
                <configuration>
                  <httpHeaders>
                    <property>
                      <name>Private-Token</name>
                      <value>${{ secrets.GITLAB_TOKEN }}</value>
                    </property>
                  </httpHeaders>
                </configuration>
              </server>
              <server>
                <id>github-prophetizo-jwave</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      - name: Build with Maven
        run: mvn -B package -U -DskipTests --file pom.xml
      - name: List built artifacts
        run: |
          echo "=== Individual Module JARs ==="
          echo "Morphiq AutoWave:"
          ls -la morphiq-autowave/target/*.jar || echo "No JARs found"
          echo ""
          echo "Morphiq Denoise:"
          ls -la morphiq-denoise/target/*.jar || echo "No JARs found"
          echo ""
          echo "=== Premium Bundle JAR ==="
          ls -la morphiq-bundle-premium/target/*.jar || echo "No JARs found"
      - name: Upload individual artifacts
        uses: actions/upload-artifact@v4
        with:
          name: individual-modules
          path: |
            morphiq-autowave/target/*.jar
            morphiq-denoise/target/*.jar
      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: morphiq-premium-bundle
          path: morphiq-bundle-premium/target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up Maven settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>gitlab-maven</id>
                <configuration>
                  <httpHeaders>
                    <property>
                      <name>Private-Token</name>
                      <value>${{ secrets.GITLAB_TOKEN }}</value>
                    </property>
                  </httpHeaders>
                </configuration>
              </server>
              <server>
                <id>github-prophetizo-jwave</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml